<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RootNamespace>UserApi</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CSharPN.Core\CSharPN.Core.csproj" />
    <ProjectReference Include="..\..\src\CSharPN.Visualizer\CSharPN.Visualizer.csproj" />
  </ItemGroup>

</Project>
